export const styles = {
  body: {
    backgroundColor: "#f4f6f4",
    fontFamily: "'DM Sans', -apple-system, sans-serif",
    margin: 0,
  },
  container: { maxWidth: 560, margin: "0 auto", padding: "32px 16px" },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    overflow: "hidden" as const,
    border: "1px solid #dde8de",
  },
  header: {
    background: "linear-gradient(155deg, #14532d 0%, #16a34a 100%)",
    padding: "28px 28px 24px",
  },
  headerBadge: {
    display: "inline-block",
    background: "rgba(255,255,255,0.18)",
    border: "1px solid rgba(255,255,255,0.22)",
    borderRadius: 20,
    padding: "4px 12px",
    fontSize: 10,
    fontWeight: 700,
    color: "#fff",
    letterSpacing: "0.05em",
    marginBottom: 12,
  },
  headerName: {
    fontSize: 20,
    fontWeight: 800,
    color: "#fff",
    margin: "0 0 4px",
    letterSpacing: "-0.02em",
  },
  headerSub: { fontSize: 12, color: "rgba(255,255,255,0.72)", margin: 0 },
  amtLabel: {
    fontSize: 10,
    color: "rgba(255,255,255,0.6)",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.07em",
    margin: "16px 0 4px",
  },
  amtBig: {
    fontSize: 36,
    fontWeight: 800,
    color: "#fff",
    fontFamily: "monospace",
    letterSpacing: "-0.04em",
    margin: 0,
  },
  amtSub: {
    fontSize: 13,
    color: "rgba(255,255,255,0.75)",
    fontFamily: "monospace",
    margin: "4px 0 0",
  },
  body_pad: { padding: "22px 28px" },
  row: {
    display: "flex",
    justifyContent: "space-between",
    padding: "7px 0",
    borderBottom: "1px solid #dde8de",
  },
  label: { fontSize: 12, color: "#8aab90", fontWeight: 500 },
  value: {
    fontSize: 12,
    color: "#111d13",
    fontWeight: 600,
    textAlign: "right" as const,
  },
  itemsBox: {
    backgroundColor: "#f0f4f1",
    borderRadius: 8,
    padding: "12px",
    margin: "12px 0",
  },
  itemRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 12,
    padding: "4px 0",
    color: "#4a6350",
    borderBottom: "1px dashed #dde8de",
  },
  totalRow: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 13,
    fontWeight: 700,
    color: "#111d13",
    paddingTop: 8,
    marginTop: 6,
    borderTop: "1.5px solid #dde8de",
  },
  cta: {
    backgroundColor: "#16a34a",
    color: "#fff",
    borderRadius: 9,
    padding: "13px 28px",
    fontSize: 14,
    fontWeight: 700,
    textDecoration: "none",
    display: "inline-block",
    marginTop: 20,
  },
  footer: {
    textAlign: "center" as const,
    marginTop: 24,
    fontSize: 11,
    color: "#8aab90",
  },
  stamp: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 20px",
    backgroundColor: "#f0f4f1",
    borderTop: "1.5px solid #bbf7d0",
  },
};
