// ─────────────────────────────────────────────────────────────────────────────
// PDF stylesheet and colour palette
// ─────────────────────────────────────────────────────────────────────────────

import { StyleSheet } from "@react-pdf/renderer";

export const COLORS = {
  green: "#16a34a",
  greenDark: "#14532d",
  greenLight: "#dcfce7",
  text: "#111d13",
  text2: "#4a6350",
  text3: "#8aab90",
  border: "#dde8de",
  surface2: "#f0f4f1",
  white: "#ffffff",
  amber: "#d97706",
  red: "#dc2626",
};

export const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    backgroundColor: COLORS.white,
    padding: 0,
  },
  header: {
    backgroundColor: COLORS.greenDark,
    padding: "28 32 24 32",
    position: "relative",
  },
  headerBadge: {
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginBottom: 10,
    alignSelf: "flex-start",
  },
  badgeTxt: {
    color: COLORS.white,
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 1,
  },
  headerName: {
    color: COLORS.white,
    fontSize: 17,
    fontFamily: "Helvetica-Bold",
    marginBottom: 2,
  },
  headerSub: { color: "rgba(255,255,255,0.72)", fontSize: 10 },
  divider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.2)",
    marginVertical: 14,
  },
  amtLabel: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 3,
  },
  amtBig: { color: COLORS.white, fontSize: 30, fontFamily: "Helvetica-Bold" },
  amtNgn: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 11,
    fontFamily: "Courier",
    marginTop: 3,
  },
  body: { padding: "20 32 28 32" },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    borderBottomColor: COLORS.border,
    borderBottomWidth: 0.5,
  },
  rowLabel: { color: COLORS.text3, fontSize: 9 },
  rowValue: {
    color: COLORS.text,
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    maxWidth: "55%",
    textAlign: "right",
  },
  itemsBox: {
    backgroundColor: COLORS.surface2,
    borderRadius: 6,
    padding: 10,
    marginVertical: 10,
  },
  itemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    borderBottomColor: COLORS.border,
    borderBottomWidth: 0.5,
  },
  itemName: { color: COLORS.text2, fontSize: 9, flex: 1 },
  itemAmt: {
    color: COLORS.text,
    fontSize: 9,
    fontFamily: "Courier-Bold",
    textAlign: "right",
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 8,
    marginTop: 6,
    borderTopColor: COLORS.border,
    borderTopWidth: 1.5,
  },
  totalLabel: {
    color: COLORS.text,
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
  },
  totalAmt: { color: COLORS.text, fontSize: 11, fontFamily: "Courier-Bold" },
  notes: {
    backgroundColor: COLORS.surface2,
    borderRadius: 6,
    padding: 10,
    marginTop: 8,
  },
  notesTxt: { color: COLORS.text2, fontSize: 9, lineHeight: 1.5 },
  stamp: {
    flexDirection: "row",
    alignItems: "center",
    padding: "10 20",
    backgroundColor: COLORS.surface2,
    borderTopColor: COLORS.greenLight,
    borderTopWidth: 1.5,
    marginTop: "auto",
  },
  stampDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: COLORS.green,
    marginRight: 8,
  },
  stampTxt: {
    color: COLORS.greenDark,
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
  },
  stampId: {
    color: COLORS.text3,
    fontSize: 8,
    fontFamily: "Courier",
    marginLeft: "auto",
  },
  twoCol: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  col: { flex: 1 },
  colLabel: {
    color: COLORS.text3,
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  colValue: { color: COLORS.text, fontSize: 10, fontFamily: "Helvetica-Bold" },
  colSub: { color: COLORS.text3, fontSize: 8, marginTop: 1 },
  overdueBox: {
    backgroundColor: "#fee2e2",
    borderRadius: 6,
    padding: "6 10",
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  overdueText: { color: COLORS.red, fontSize: 9, fontFamily: "Helvetica-Bold" },
});
